-- Seed Kenya Geography Data

-- Insert Counties
INSERT INTO counties (name, population, country) SELECT 'Nairobi', 4397073, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Nairobi');
INSERT INTO counties (name, population, country) SELECT 'Kiambu', 2417735, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kiambu');
INSERT INTO counties (name, population, country) SELECT 'Nyeri', 759164, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Nyeri');
INSERT INTO counties (name, population, country) SELECT 'Kirinyaga', 610411, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kirinyaga');
INSERT INTO counties (name, population, country) SELECT 'Murang''a', 1056640, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Murang''a');
INSERT INTO counties (name, population, country) SELECT 'Nyandarua', 638289, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Nyandarua');
INSERT INTO counties (name, population, country) SELECT 'Mombasa', 1208333, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Mombasa');
INSERT INTO counties (name, population, country) SELECT 'Kilifi', 1453787, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kilifi');
INSERT INTO counties (name, population, country) SELECT 'Kwale', 866820, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kwale');
INSERT INTO counties (name, population, country) SELECT 'Lamu', 143920, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Lamu');
INSERT INTO counties (name, population, country) SELECT 'Taita Taveta', 340671, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Taita Taveta');
INSERT INTO counties (name, population, country) SELECT 'Tana River', 315943, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Tana River');
INSERT INTO counties (name, population, country) SELECT 'Embu', 608599, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Embu');
INSERT INTO counties (name, population, country) SELECT 'Isiolo', 268002, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Isiolo');
INSERT INTO counties (name, population, country) SELECT 'Kitui', 1136187, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kitui');
INSERT INTO counties (name, population, country) SELECT 'Machakos', 1421932, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Machakos');
INSERT INTO counties (name, population, country) SELECT 'Makueni', 987653, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Makueni');
INSERT INTO counties (name, population, country) SELECT 'Marsabit', 459785, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Marsabit');
INSERT INTO counties (name, population, country) SELECT 'Meru', 1545714, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Meru');
INSERT INTO counties (name, population, country) SELECT 'Tharaka Nithi', 393177, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Tharaka Nithi');
INSERT INTO counties (name, population, country) SELECT 'Garissa', 841353, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Garissa');
INSERT INTO counties (name, population, country) SELECT 'Mandera', 1200000, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Mandera');
INSERT INTO counties (name, population, country) SELECT 'Wajir', 781263, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Wajir');
INSERT INTO counties (name, population, country) SELECT 'Homa Bay', 1131950, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Homa Bay');
INSERT INTO counties (name, population, country) SELECT 'Kisii', 1266860, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kisii');
INSERT INTO counties (name, population, country) SELECT 'Kisumu', 1155574, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kisumu');
INSERT INTO counties (name, population, country) SELECT 'Migori', 1116436, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Migori');
INSERT INTO counties (name, population, country) SELECT 'Nyamira', 605576, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Nyamira');
INSERT INTO counties (name, population, country) SELECT 'Siaya', 993183, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Siaya');
INSERT INTO counties (name, population, country) SELECT 'Baringo', 666763, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Baringo');
INSERT INTO counties (name, population, country) SELECT 'Bomet', 875689, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Bomet');
INSERT INTO counties (name, population, country) SELECT 'Elgeyo Marakwet', 454480, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Elgeyo Marakwet');
INSERT INTO counties (name, population, country) SELECT 'Kajiado', 1117840, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kajiado');
INSERT INTO counties (name, population, country) SELECT 'Kericho', 901777, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kericho');
INSERT INTO counties (name, population, country) SELECT 'Laikipia', 518560, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Laikipia');
INSERT INTO counties (name, population, country) SELECT 'Nakuru', 2162202, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Nakuru');
INSERT INTO counties (name, population, country) SELECT 'Nandi', 885711, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Nandi');
INSERT INTO counties (name, population, country) SELECT 'Narok', 1157873, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Narok');
INSERT INTO counties (name, population, country) SELECT 'Samburu', 310327, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Samburu');
INSERT INTO counties (name, population, country) SELECT 'Trans Nzoia', 990341, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Trans Nzoia');
INSERT INTO counties (name, population, country) SELECT 'Turkana', 926976, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Turkana');
INSERT INTO counties (name, population, country) SELECT 'Uasin Gishu', 1163186, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Uasin Gishu');
INSERT INTO counties (name, population, country) SELECT 'West Pokot', 621241, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'West Pokot');
INSERT INTO counties (name, population, country) SELECT 'Bungoma', 1670570, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Bungoma');
INSERT INTO counties (name, population, country) SELECT 'Busia', 893681, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Busia');
INSERT INTO counties (name, population, country) SELECT 'Kakamega', 1867579, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Kakamega');
INSERT INTO counties (name, population, country) SELECT 'Vihiga', 590013, 'Kenya' WHERE NOT EXISTS (SELECT 1 FROM counties WHERE name = 'Vihiga');

-- Insert Constituencies
INSERT INTO constituencies (name, county_id) SELECT 'Westlands', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Westlands' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Dagoretti North', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Dagoretti North' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Dagoretti South', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Dagoretti South' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Langata', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Langata' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kibra', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kibra' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Roysambu', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Roysambu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kasarani', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kasarani' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Ruaraka', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Ruaraka' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Embakasi South', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Embakasi South' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Embakasi North', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Embakasi North' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Embakasi Central', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Embakasi Central' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Embakasi East', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Embakasi East' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Embakasi West', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Embakasi West' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Makadara', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Makadara' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kamukunji', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kamukunji' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Starehe', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Starehe' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mathare', id FROM counties WHERE name = 'Nairobi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mathare' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Gatundu South', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Gatundu South' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Gatundu North', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Gatundu North' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Juja', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Juja' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Thika Town', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Thika Town' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Ruiru', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Ruiru' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Githunguri', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Githunguri' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kiambu', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kiambu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kiambaa', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kiambaa' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kabete', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kabete' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kikuyu', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kikuyu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Limuru', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Limuru' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Lari', id FROM counties WHERE name = 'Kiambu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Lari' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Changamwe', id FROM counties WHERE name = 'Mombasa' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Changamwe' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Jomvu', id FROM counties WHERE name = 'Mombasa' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Jomvu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kisauni', id FROM counties WHERE name = 'Mombasa' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kisauni' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Nyali', id FROM counties WHERE name = 'Mombasa' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Nyali' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Likoni', id FROM counties WHERE name = 'Mombasa' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Likoni' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mvita', id FROM counties WHERE name = 'Mombasa' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mvita' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kisumu East', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kisumu East' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kisumu West', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kisumu West' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kisumu Central', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kisumu Central' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Seme', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Seme' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Nyando', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Nyando' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Muhoroni', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Muhoroni' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Nyakach', id FROM counties WHERE name = 'Kisumu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Nyakach' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Nakuru Town East', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Nakuru Town East' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Nakuru Town West', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Nakuru Town West' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Bahati', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Bahati' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Gilgil', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Gilgil' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Naivasha', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Naivasha' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kuresoi South', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kuresoi South' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kuresoi North', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kuresoi North' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Molo', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Molo' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Njoro', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Njoro' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Rongai', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Rongai' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Subukia', id FROM counties WHERE name = 'Nakuru' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Subukia' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Lugari', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Lugari' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Likuyani', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Likuyani' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Malava', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Malava' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Lurambi', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Lurambi' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Navakholo', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Navakholo' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mumias West', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mumias West' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mumias East', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mumias East' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Matungu', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Matungu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Butere', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Butere' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Khwisero', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Khwisero' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Shinyalu', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Shinyalu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Ikolomani', id FROM counties WHERE name = 'Kakamega' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Ikolomani' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Machakos Town', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Machakos Town' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mavoko', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mavoko' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kathiani', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kathiani' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Yatta', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Yatta' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kangundo', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kangundo' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Matungulu', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Matungulu' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mwala', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mwala' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Masinga', id FROM counties WHERE name = 'Machakos' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Masinga' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kilifi North', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kilifi North' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kilifi South', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kilifi South' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Ganze', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Ganze' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kaloleni', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kaloleni' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Malindi', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Malindi' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Magarini', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Magarini' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Rabai', id FROM counties WHERE name = 'Kilifi' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Rabai' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Bumula', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Bumula' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kabuchai', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kabuchai' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kanduyi', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kanduyi' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kimilili', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kimilili' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Mt Elgon', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Mt Elgon' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Sirisia', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Sirisia' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Tongaren', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Tongaren' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Webuye East', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Webuye East' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Webuye West', id FROM counties WHERE name = 'Bungoma' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Webuye West' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Ainabkoi', id FROM counties WHERE name = 'Uasin Gishu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Ainabkoi' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kapseret', id FROM counties WHERE name = 'Uasin Gishu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kapseret' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Kesses', id FROM counties WHERE name = 'Uasin Gishu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Kesses' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Moiben', id FROM counties WHERE name = 'Uasin Gishu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Moiben' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Soy', id FROM counties WHERE name = 'Uasin Gishu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Soy' AND county_id = counties.id);
INSERT INTO constituencies (name, county_id) SELECT 'Turbo', id FROM counties WHERE name = 'Uasin Gishu' AND NOT EXISTS (SELECT 1 FROM constituencies WHERE name = 'Turbo' AND county_id = counties.id);

-- Insert Wards
INSERT INTO wards (name, constituency_id) SELECT 'Kitisuru', id FROM constituencies WHERE name = 'Westlands' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kitisuru' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Parklands/Highridge', id FROM constituencies WHERE name = 'Westlands' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Parklands/Highridge' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Karura', id FROM constituencies WHERE name = 'Westlands' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Karura' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kangemi', id FROM constituencies WHERE name = 'Westlands' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kangemi' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Mountain View', id FROM constituencies WHERE name = 'Westlands' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Mountain View' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Pumwani', id FROM constituencies WHERE name = 'Kamukunji' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Pumwani' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Eastleigh North', id FROM constituencies WHERE name = 'Kamukunji' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Eastleigh North' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Eastleigh South', id FROM constituencies WHERE name = 'Kamukunji' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Eastleigh South' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Airbase', id FROM constituencies WHERE name = 'Kamukunji' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Airbase' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'California', id FROM constituencies WHERE name = 'Kamukunji' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'California' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Nairobi Central', id FROM constituencies WHERE name = 'Starehe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Nairobi Central' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Ngara', id FROM constituencies WHERE name = 'Starehe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Ngara' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Ziwani/Kariokor', id FROM constituencies WHERE name = 'Starehe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Ziwani/Kariokor' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Landimawe', id FROM constituencies WHERE name = 'Starehe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Landimawe' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Nairobi South', id FROM constituencies WHERE name = 'Starehe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Nairobi South' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Laini Saba', id FROM constituencies WHERE name = 'Kibra' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Laini Saba' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Lindi', id FROM constituencies WHERE name = 'Kibra' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Lindi' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Makina', id FROM constituencies WHERE name = 'Kibra' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Makina' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Woodley/Kenyatta Golf Course', id FROM constituencies WHERE name = 'Kibra' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Woodley/Kenyatta Golf Course' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Sarang''ombe', id FROM constituencies WHERE name = 'Kibra' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Sarang''ombe' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Upper Savannah', id FROM constituencies WHERE name = 'Embakasi East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Upper Savannah' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Lower Savannah', id FROM constituencies WHERE name = 'Embakasi East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Lower Savannah' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Embakasi', id FROM constituencies WHERE name = 'Embakasi East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Embakasi' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Utawala', id FROM constituencies WHERE name = 'Embakasi East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Utawala' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Mihango', id FROM constituencies WHERE name = 'Embakasi East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Mihango' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Biashara', id FROM constituencies WHERE name = 'Ruiru' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Biashara' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Gatongora', id FROM constituencies WHERE name = 'Ruiru' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Gatongora' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kahawa Sukari', id FROM constituencies WHERE name = 'Ruiru' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kahawa Sukari' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kahawa Wendani', id FROM constituencies WHERE name = 'Ruiru' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kahawa Wendani' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kiuu', id FROM constituencies WHERE name = 'Ruiru' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kiuu' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Mwihoko', id FROM constituencies WHERE name = 'Ruiru' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Mwihoko' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Township', id FROM constituencies WHERE name = 'Thika Town' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Township' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kamenu', id FROM constituencies WHERE name = 'Thika Town' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kamenu' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Hospital', id FROM constituencies WHERE name = 'Thika Town' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Hospital' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Gatuanyaga', id FROM constituencies WHERE name = 'Thika Town' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Gatuanyaga' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Ngoliba', id FROM constituencies WHERE name = 'Thika Town' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Ngoliba' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Port Reitz', id FROM constituencies WHERE name = 'Changamwe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Port Reitz' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kipevu', id FROM constituencies WHERE name = 'Changamwe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kipevu' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Airport', id FROM constituencies WHERE name = 'Changamwe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Airport' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Changamwe', id FROM constituencies WHERE name = 'Changamwe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Changamwe' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Chaani', id FROM constituencies WHERE name = 'Changamwe' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Chaani' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Mji Wa Kale/Makadara', id FROM constituencies WHERE name = 'Mvita' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Mji Wa Kale/Makadara' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Tudor', id FROM constituencies WHERE name = 'Mvita' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Tudor' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Tononoka', id FROM constituencies WHERE name = 'Mvita' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Tononoka' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Shimanzi/Ganjoni', id FROM constituencies WHERE name = 'Mvita' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Shimanzi/Ganjoni' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Majengo', id FROM constituencies WHERE name = 'Mvita' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Majengo' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kajulu', id FROM constituencies WHERE name = 'Kisumu East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kajulu' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kolwa East', id FROM constituencies WHERE name = 'Kisumu East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kolwa East' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Manyatta B', id FROM constituencies WHERE name = 'Kisumu East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Manyatta B' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kolwa Central', id FROM constituencies WHERE name = 'Kisumu East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kolwa Central' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Nyalenda A', id FROM constituencies WHERE name = 'Kisumu East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Nyalenda A' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Market Milimani', id FROM constituencies WHERE name = 'Kisumu Central' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Market Milimani' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kondele', id FROM constituencies WHERE name = 'Kisumu Central' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kondele' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Nyalenda B', id FROM constituencies WHERE name = 'Kisumu Central' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Nyalenda B' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Migosi', id FROM constituencies WHERE name = 'Kisumu Central' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Migosi' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Shaurimoyo Kaloleni', id FROM constituencies WHERE name = 'Kisumu Central' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Shaurimoyo Kaloleni' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Biashara', id FROM constituencies WHERE name = 'Nakuru Town East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Biashara' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kivumbini', id FROM constituencies WHERE name = 'Nakuru Town East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kivumbini' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Flamingo', id FROM constituencies WHERE name = 'Nakuru Town East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Flamingo' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Menengai West', id FROM constituencies WHERE name = 'Nakuru Town East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Menengai West' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Nakuru East', id FROM constituencies WHERE name = 'Nakuru Town East' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Nakuru East' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Butsotso East', id FROM constituencies WHERE name = 'Lurambi' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Butsotso East' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Butsotso South', id FROM constituencies WHERE name = 'Lurambi' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Butsotso South' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Butsotso Central', id FROM constituencies WHERE name = 'Lurambi' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Butsotso Central' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Sheywe', id FROM constituencies WHERE name = 'Lurambi' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Sheywe' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Mahiakalo', id FROM constituencies WHERE name = 'Lurambi' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Mahiakalo' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Shirugu-Mugai', id FROM constituencies WHERE name = 'Lurambi' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Shirugu-Mugai' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Athi River', id FROM constituencies WHERE name = 'Mavoko' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Athi River' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kinanie', id FROM constituencies WHERE name = 'Mavoko' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kinanie' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Muthwani', id FROM constituencies WHERE name = 'Mavoko' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Muthwani' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Syokimau/Mulolongo', id FROM constituencies WHERE name = 'Mavoko' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Syokimau/Mulolongo' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Simat/Kapseret', id FROM constituencies WHERE name = 'Kapseret' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Simat/Kapseret' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Kipkenyo', id FROM constituencies WHERE name = 'Kapseret' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Kipkenyo' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Ngeria', id FROM constituencies WHERE name = 'Kapseret' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Ngeria' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Megun', id FROM constituencies WHERE name = 'Kapseret' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Megun' AND constituency_id = constituencies.id);
INSERT INTO wards (name, constituency_id) SELECT 'Langas', id FROM constituencies WHERE name = 'Kapseret' AND NOT EXISTS (SELECT 1 FROM wards WHERE name = 'Langas' AND constituency_id = constituencies.id);
